runtime: python311

entrypoint: gunicorn --timeout 500 -b :$PORT backend:app

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: auto

env_variables:
  FLASK_ENV: development
  FLASK_APP: backend.py
  BUCKET_URL: "capstone-a4973.firebasestorage.app"

instance_class: F4_1G